일년 전 마무리한 졸업작품을 확인하고 싶은데,,, run이 되지 않아 화나는 문제에 대하여 , , ,

### No python interpreter configured for the project

![image](https://user-images.githubusercontent.com/39394592/148631872-657f0dcc-a2f8-45d3-aeaf-b0c03804ce83.png)
- `Configure Python interpreter` > `Interpreter Settings...`

![image](https://user-images.githubusercontent.com/39394592/148631942-2928bc29-30c3-4d2f-9a48-10f13fd2f5fe.png)
- 톱니바퀴 클릭 > `Add...`

- `System interpreter`에서 python.exe 경로 연결

![image](https://user-images.githubusercontent.com/39394592/148632089-b470946b-1743-4412-8301-7d8eb20667fb.png)
- run


### Error : django.core.exceptions.ImproperlyConfigured
![image](https://user-images.githubusercontent.com/39394592/148632097-f1ab0e61-b769-47b3-9b45-4852413a7276.png)
- 오류난 곳 경로를 보니 db 관련 에러인 것 같음
- 테스트 겸 터미널에서 마이그레이션

```
python manage.py makemigrations
```

### Error : ModuleNotFoundError : No module named 'allauth'
![image](https://user-images.githubusercontent.com/39394592/148632397-a176b7a7-c51f-4b97-830d-0e1c45aba195.png)
- 모듈을 찾을 수 없다고 나옴

- [참고 : ImportError: No module named allauth. Django](https://pretagteam.com/question/importerror-no-module-named-allauth-django)

```
pip install django -allauth
```
> 안 됨

```
pip install django_allauth
```
> 됨

### Error : ModuleNotFoundError : No module named 'mathfilters'
```
python manage.py makemigrations
```

![image](https://user-images.githubusercontent.com/39394592/148632462-94350987-227d-4b09-b3dd-f0f772662c2f.png)
- 위랑 똑같은 경우이겠거니 하고 pip install ㄱㄱ

```
pip install django_mathfilters
```
> 됨

### Warnings : Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
```
python manage.py makemigrations
```

![image](https://user-images.githubusercontent.com/39394592/148632514-c3257496-9f4c-424a-8da1-d0689694980a.png)

- [참고 : Django 3.2 release notes](https://docs.djangoproject.com/en/3.2/releases/3.2/#customizing-type-of-auto-created-primary-keys)
- [참고 : Auto-create primary key used when not defining a primary key type warning in Django](https://stackoverflow.com/questions/66971594/auto-create-primary-key-used-when-not-defining-a-primary-key-type-warning-in-dja)

```
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
```
- 영어라서 뭔 소린지 잘 모르겠는데 장고 3.2부터는 기본키에 대한 설정을 해줘야 되는 것 같음
- `settings.py`에 위 코드 추가

### Error : Cannot use ImageField because Pillow is not installed.
```
python manage.py makemigrations
```

![image](https://user-images.githubusercontent.com/39394592/148632657-d4edb9c2-5a7d-4116-8e77-8284a7bf35ef.png)
- 이건 친절하게 힌트에 `HINT: Get Pillow at https://pypi.org/project/Pillow/ or run command "python -m pip install Pillow".`
라고 써져있었음

```
pip install Pillow
```

### Error : django.core.exceptions.ImproperlyConfigured
- 깔 거 다 깔고 났더니 다시 첫 번째 에러로 돌아옴
- 검색해 보니까 Startproject 명령어로 생성되지 않은 파일에서 장고를 사용하면 나타나는 문제 같은데,, , ㅜ~~~ 
