# 예외처리(Exception)


: 예외가 발생된 경우 예외를 처리하기 위한 방법 
> [Oracle - Class Exception](https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/lang/Exception.html)

### 예외처리를 처리하는 클래스(Class)

- Throwable : 프로그램 오류에 관련된 최상위 클래스
  - Error : 하드웨어에 의해 발생하는 오류 처리를 위한 상위 클래스
  - Exception : 소프트웨어에 의해 발생하는 오류 처리하기 위한 상위 클래스

#
 
#### 예외처리 방법 : 실행 관련 예외는 예외처리를 하지 않으면 기본적으로 JVM 자동적으로 예외처리


#### 1. 예외가 발생될 명령이 선언된 메소드에서 예외처리

  - 형식
  ```java
  try {
    //예외가 발생될수 있는 명령; ... 
    } catch(예외클래스 참조변수) {  
      //예외처리명령; ...

      //Throwable.getMessage() : 예외 인스턴스의 오류 메세지를 반환하는 메소드
      System.out.println("예외 메세지 = "+e.getMessage());

      //Throwable.printStackTrace() : 예외가 발생된 경로를 상세하게 표현하여 출력하는 메소드
      e.printStackTrace();
      } finally {
        //무조건 실행 명령; ...
      }
  ```
  
- try 영역에서 예외가 발생될 경우 예외 인스턴스 생성
- catch 영역에서 예외 인스턴스를 전달받아 예외 처리 - 프로그램 흐름 이동
- catch 영역은 여러 번 선언 가능
- finally 영역에는 예외 발생에 상관없이 무조건 실행될 명령 작성 - 생략

 #

[실습] [ExceptionHandleApp.java](https://github.com/swanstoz/TIL/blob/master/JAVA/exception/ExceptionHandleApp.java)

- try-catch 구문을 통한 예외처리

```java
public class ExceptionHandleApp {
	public static void main(String[] args) {
		int[] array={10,20,30,40,50};
		
		//예외가 발생 가능한 명령을 try 영역에 작성 //속도 느려짐
		// => 예외가 발생될 경우 예외 관련 인스턴스 생성 
		// => catch 구문에서 예외 인스턴스를 전달받아 예외 처리
		try {
			//배열의 요소 표현시 첨자를 잘못 사용한 경우 ArrayIndexOutOfBoundsException 발생
			// => ArrayIndexOutOfBoundsException이 발생된 경우 JVM에 의해 자동으로 예외 처리
			// => JVM의 예외처리는 예외가 발생된 경로를 상세하게 표현하여 출력 - 개발자 중심
			// => 사용자 중심의 프로그램을 작성하기 위해 직접 예외 처리하는 것을 권장
			for(int i=0;i<=array.length;i++) {
				System.out.println("array["+i+"] = "+array[i]);
			}
			
			//예외가 발생된 명령 하단에 존재하는 명령은 미실행
			// => 예외가 발생되면 catch 구문으로 스레드(프로그램의 실행 흐름) 이동
			System.out.println("[메세지]프로그램이 정상적으로 실행 되었습니다.");
		} catch (ArrayIndexOutOfBoundsException e) {//예외 인스턴스를 전달받아 참조변수에 저장
			//catch 영역에 설정된 예외 클래스에 대한 예외 처리 명령 작성 - 메세지 출력
			//System.out.println("[에러]프로그램 실행에 예기치 못한 오류가 발생 되었습니다.");
			
			//Throwable.getMessage() : 예외 인스턴스의 오류 메세지를 반환하는 메소드
//			System.out.println("예외 메세지 = "+e.getMessage());
			
			//Throwable.printStackTrace() : 예외가 발생된 경로를 상세하게 표현하여 출력하는 메소드
			e.printStackTrace();
		} finally {
			//예외와 상관없이 무조건 실행될 명령을 작성하는 영역 : 생략 가능 
			// => 자원에 대한 제거 명령을 구현할 경우 사용
			System.out.println("[메세지]무조건 실행되는 명령");
		}
	}
}
```

---

#### 2) 예외가 발생될 명령이 선언된 메소드에서 예외 전달

- 예외가 전달된 메소드를 호출할 경우 try 구문을 이용하여 예외처리   
- 형식

```java
접근지정자 반환형 메소드명(파라메터,...) throws 예외클래스,예외클래스,... {
                예외 발생 명령;
                . . .
}
```    
- 예외를 전달하여 한번에 예외처리 하고자 할 경우 사용

 #

[실습][ExceptionThrowsApp.java](https://github.com/swanstoz/TIL/blob/master/JAVA/exception/ExceptionThrowsApp.java)

- throws 를 사용한 예외 전달과 try-catch를 통한 예외처리

```java
public class ExceptionThrowsApp {
	//메소드의 명령 실행시 발생되는 예외를 throws 키워드로 전달
	// => 예외를 전달하는 메소드를 호출하면 예외 발생
	public static void display() throws ArrayIndexOutOfBoundsException {
		int[] array= {10,20,30,40,50};
		
		//예외(ArrayIndexOutOfBoundsException) 발생 명령
		for(int i=0;i<array.length;i++) {
			System.out.println("array["+i+"] = "+array[i]);
		}
	}
	
	public static void main(String[] args) {
		try {
			//static 메소드는 클래스를 이용하여 호출
			//ExceptionThrowsApp.display();
		
		
			//같은 클래스의 static 메소드는 클래스명을 생략하여 호출 가능
			//예외(ArrayIndexOutOfBoundsException)을 전달하는 메소드 호출 - 예외 발생
			display(); 
		}catch(ArrayIndexOutOfBoundsException e) {
			System.out.println("[에러]프로그램 실행에 예기치 못한 오류가 발생 되었습니다.");
		}
	}
}
```

#

[실습][CalcApp.java](https://github.com/swanstoz/TIL/blob/master/JAVA/exception/CalcApp.java)

- throws 를 사용한 예외 전달과 try-catch를 통한 다중 예외처리

```java
import java.util.InputMismatchException;
import java.util.Scanner;

//키보드로 정수값 2개를 입력받아 나눈 몫을 출력하는 프로그램 작성
public class CalcApp {
	public CalcApp() throws InputMismatchException, ArithmeticException {
		// TODO Auto-generated constructor stub
		Scanner scanner=new Scanner(System.in);
		
		System.out.println("첫번재 정수 입력 >> ");
		//Scanner.nextInt() : 입력값을 정수값으로 변환하여 반환하는 메소드
		// => 입력값이 정수값으로 변환되지 못할 경우 InputMismatchException
		int num1=scanner.nextInt();
		
		System.out.println("두번재 정수 입력 >> ");
		int num2=scanner.nextInt();
		
		//0으로 나눈 경우 ArithmeticException 발생
		System.out.println("[결과]"+num1+" / "+num2+" = "+(num1/num2));
		
		scanner.close();
	}
	
	public static void main(String[] args) {
		/*
		try{
			new CalcApp(); //생성자를 불러와 인스턴스 생성 >> 생성자의 명령 실행
		}catch (InputMismatchException e) {
			// TODO: handle exception
			System.out.println("[에러]정수만 입력 가능합니다.");
		}catch (ArithmeticException e) {
			System.out.println("[에러]0으로 나눌 수 없습니다.");
		}catch (Exception e) {
			//Exception : 모든 예외 클래스의 부모 클래스
			// => 모든 예외를 전달받아 예외 처리
			System.out.println("[에러]프로그램에 예기치 못한 오류가 발생되었습니다.");
		}
		*/
		try{
			new CalcApp(); //생성자를 불러와 인스턴스 생성 >> 생성자의 명령 실행
		}catch (InputMismatchException | ArithmeticException e) {
			// JDK 7 이상에서는 예외 클래스를 | 연산자로 연결하여 예외 처리 가능
			System.out.println("[에러]형식에 맞게 값을 입력해 주세요.");
		}catch (Exception e) {
			//Exception : 모든 예외 클래스의 부모 클래스
			// => 모든 예외를 전달받아 예외 처리
			System.out.println("[에러]프로그램에 예기치 못한 오류가 발생되었습니다.");
		}
		
	}
}
```

---

#### 발생 가능한 예외 확인하기

1) 콘솔 창에 뜬 JVM 예외 처리 메시지 확인 

2) Ctrl+메소드 클릭으로 해당 클래스로 이동 후 발생 가능한 예외 확인

---

#### 예외클래스 작성 방법 : Exception 클래스를 상속받아 작성
- 직접 만든 예외클래스를 사용하려면 직접 예외를 작성해야 한다

 

- 형식
```java
public class 예외클래스 extends Exception {
  public 예외클래스() { }
                
  public 예외클래스(String message) {
    super(message);
  }
}
```
 

#### 인위적 예외 발생
- 형식 

```java
if(조건문) throw new 예외클래스(메세지);
```

#

[실습][PasswordMatchApp.java](https://github.com/swanstoz/TIL/blob/master/JAVA/exception/PasswordMatchApp.java)

- 비밀번호 비교하는 App 작성(비밀번호가 다를 시 예외 처리)


```java
import java.util.InputMismatchException;
import java.util.Scanner;

//키보드로 정수값을 입력받아 저장된 비밀번호와 비교하여 결과를 출력하는 프로그램
public class PasswordMatchApp {
	public static void main(String[] args) {
		
		/*
		Scanner scanner=new Scanner(System.in);
		
		System.out.print("비밀번호 입력 >> ");
		int password=scanner.nextInt();
		
		if(password==1234) {
			System.out.println("[결과]입력된 비밀번호가 맞습니다.");
		} else {
			System.out.println("[결과]입력된 비밀번호가 다릅니다.");
		}
		
		scanner.close();
		*/
		
		Scanner scanner=new Scanner(System.in);
		
		try {
			System.out.print("비밀번호 입력 >> ");
			int password=scanner.nextInt(); //InputMismatchException
			
			if(password!=1234) {//비밀번호가 맞지 않을 경우
				//인위적으로 예외 발생 - 예외 인스턴스를 생성하여 전달
				// => JVM에 의해 자동으로 예외 처리되는 예외가 아니므로 예외 처리하지 않으면 에러 발생
				throw new PasswordMismatchException("[결과]입력된 비밀번호가 다릅니다.");
			}
			System.out.println("[결과]입력된 비밀번호가 맞습니다.");
		} catch (InputMismatchException e) {
			System.out.println("[에러]숫자만 입력 가능합니다.");
		} catch (PasswordMismatchException e) {
			System.out.println(e.getMessage());
		} finally {
			//사용 자원을 제거하는 명령 >> 예외에 상관없이 무조건 실행
			scanner.close();
		}
	}//end of main
}//end of class
```

#

[실습][PasswordMismatchException.java](https://github.com/swanstoz/TIL/blob/master/JAVA/exception/PasswordMismatchException.java)

- 예외 클래스 작성

```java
//Exception 클래스 상속받아 예외 클래스 작성
public class PasswordMismatchException extends Exception{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	public PasswordMismatchException() {
		// TODO Auto-generated constructor stub
	}
	
	public PasswordMismatchException(String message) {
		// TODO Auto-generated constructor stub
		super(message);
	}
}
```
